/**
 * Schémas de création alignés sur les StoreRequest de budental_compta_api.
 */
export const resourceForms = {
  journaux: {
    createLabel: 'Nouveau journal',
    endpoint: 'journals',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
      { key: 'type_journal_id', label: 'Type de journal', type: 'lookup', lookup: 'typeJournals', required: true },
    ],
  },
  tiers: {
    createLabel: 'Nouveau tiers',
    editLabel: 'Modifier le tiers',
    endpoint: 'tiers',
    fields: [
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
      { key: 'nom_complet', label: 'Nom complet', type: 'text' },
      { key: 'contact', label: 'Contact', type: 'text' },
      { key: 'abrege', label: 'Abréviation', type: 'text' },
      { key: 'compte_collectif_id', label: 'Compte collectif', type: 'lookup', lookup: 'comptes' },
      { key: 'type_tiers_id', label: 'Type de tiers', type: 'lookup', lookup: 'typeTiers', required: true },
      { key: 'adresse', label: 'Adresse', type: 'text' },
      { key: 'telephone', label: 'Téléphone', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'nif', label: 'NIF', type: 'text' },
      { key: 'actif', label: 'Actif', type: 'boolean', default: true },
    ],
  },
  banques: {
    createLabel: 'Nouvelle banque',
    endpoint: 'banques',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
      { key: 'numero_compte', label: 'N° compte', type: 'text' },
      { key: 'iban', label: 'IBAN', type: 'text' },
      { key: 'swift', label: 'SWIFT', type: 'text' },
      { key: 'actif', label: 'Actif', type: 'boolean', default: true },
    ],
  },
  comptes: {
    createLabel: 'Nouveau compte',
    endpoint: 'comptes',
    fields: [
      { key: 'numero', label: 'Numéro', type: 'text', required: true },
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
    ],
  },
  budgets: {
    createLabel: 'Nouveau budget',
    endpoint: 'budgets',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
      { key: 'exercice_id', label: 'Exercice', type: 'lookup', lookup: 'exercices', required: true },
      { key: 'departement_id', label: 'Département', type: 'lookup', lookup: 'departements', required: true },
      { key: 'section_id', label: 'Section', type: 'lookup', lookup: 'sections', required: true },
      { key: 'section_analytique_id', label: 'Section analytique', type: 'lookup', lookup: 'sections', required: true },
      { key: 'poste_budgetaire_id', label: 'Poste budgétaire', type: 'lookup', lookup: 'postes', required: true },
      { key: 'montant_prevu', label: 'Montant prévu', type: 'number', default: 0, required: true },
      { key: 'montant_revise', label: 'Montant révisé', type: 'number', default: 0, required: true },
      { key: 'montant_engage', label: 'Montant engagé', type: 'number', default: 0, required: true },
      { key: 'montant_realise', label: 'Montant réalisé', type: 'number', default: 0, required: true },
      { key: 'actif', label: 'Actif', type: 'boolean', default: true },
    ],
  },
  postes: {
    createLabel: 'Nouveau poste budgétaire',
    endpoint: 'poste-budgetaires',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
      { key: 'type_budget_id', label: 'Type de budget', type: 'lookup', lookup: 'typeBudgets', required: true },
      { key: 'compte_id', label: 'Compte', type: 'lookup', lookup: 'comptes', required: true },
      { key: 'actif', label: 'Actif', type: 'boolean', default: true },
    ],
  },
  immobilisations: {
    createLabel: 'Nouvelle immobilisation',
    editLabel: 'Modifier l’immobilisation',
    endpoint: 'immobilisations',
    fields: [
      { key: 'societe_id', label: 'Société', type: 'lookup', lookup: 'societes', required: true },
      { key: 'compte_id', label: 'Compte', type: 'lookup', lookup: 'comptes', required: true },
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'libelle', label: 'Libellé', type: 'text', required: true },
      { key: 'date_acquisition', label: 'Date acquisition', type: 'date', required: true },
      { key: 'date_mise_en_service', label: 'Date mise en service', type: 'date' },
      { key: 'taux', label: 'Taux', type: 'number' },
      { key: 'valeur_origine', label: 'Valeur origine', type: 'number', default: 0, required: true },
      { key: 'valeur_residuelle', label: 'Valeur résiduelle', type: 'number', default: 0 },
      { key: 'duree_annees', label: 'Durée années', type: 'number', default: 1, required: true },
      {
        key: 'statut',
        label: 'Statut',
        type: 'select',
        default: 'en_service',
        required: true,
        options: [
          { value: 'en_attente', label: 'En attente' },
          { value: 'en_service', label: 'En service' },
          { value: 'sortie', label: 'Sortie' },
        ],
      },
      { key: 'date_sortie', label: 'Date sortie', type: 'date' },
      { key: 'valeur_cession', label: 'Valeur cession', type: 'number' },
    ],
  },
  amortissements: {
    createLabel: 'Nouvel amortissement',
    editLabel: 'Modifier l’amortissement',
    endpoint: 'amortissements',
    fields: [
      { key: 'immobilisation_id', label: 'Immobilisation', type: 'lookup', lookup: 'immobilisations', required: true },
      { key: 'exercice_id', label: 'Exercice', type: 'lookup', lookup: 'exercices', required: true },
      { key: 'periode_id', label: 'Période', type: 'lookup', lookup: 'periodes' },
      { key: 'ecriture_id', label: 'Écriture générée', type: 'lookup', lookup: 'ecritures' },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        default: 'lineaire',
        required: true,
        options: [
          { value: 'lineaire', label: 'Linéaire' },
          { value: 'degressif', label: 'Dégressif' },
        ],
      },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'montant', label: 'Montant', type: 'number', default: 0, required: true },
      { key: 'cumul', label: 'Cumul', type: 'number' },
      { key: 'vnc', label: 'VNC', type: 'number' },
    ],
  },
  pieces: {
    createLabel: 'Nouvelle pièce',
    editLabel: 'Modifier la pièce',
    endpoint: 'piece-comptables',
    fields: [
      { key: 'modele', label: 'Modèle', type: 'text' },
      { key: 'journal_id', label: 'Journal', type: 'lookup', lookup: 'journals', required: true },
      { key: 'exercice_id', label: 'Exercice', type: 'lookup', lookup: 'exercices', required: true },
      { key: 'periode_id', label: 'Période', type: 'lookup', lookup: 'periodes', required: true },
      { key: 'numero_piece', label: 'N° pièce', type: 'text', required: true },
      { key: 'reference', label: 'Référence', type: 'text' },
      { key: 'date_piece', label: 'Date pièce', type: 'date', required: true },
      { key: 'date_comptable', label: 'Date comptable', type: 'date', required: true },
      { key: 'libelle', label: 'Libellé', type: 'text' },
      { key: 'total_debit', label: 'Total débit', type: 'number', default: 0, required: true },
      { key: 'total_credit', label: 'Total crédit', type: 'number', default: 0, required: true },
      {
        key: 'etat',
        label: 'État',
        type: 'select',
        default: 'brouillon',
        required: true,
        options: [
          { value: 'brouillon', label: 'Brouillon' },
          { value: 'validee', label: 'Validée' },
          { value: 'comptabilisee', label: 'Comptabilisée' },
          { value: 'annulee', label: 'Annulée' },
        ],
      },
      { key: 'date_validation', label: 'Date validation', type: 'date' },
      { key: 'date_comptabilisation', label: 'Date comptabilisation', type: 'date' },
      { key: 'date_annulation', label: 'Date annulation', type: 'date' },
      { key: 'motif_annulation', label: 'Motif annulation', type: 'text' },
    ],
  },
  societes: {
    createLabel: 'Nouvelle société',
    editLabel: 'Modifier la société',
    endpoint: 'societes',
    fields: [
      { key: 'raison_sociale', label: 'Raison sociale', type: 'text', required: true },
      { key: 'nif', label: 'NIF', type: 'text' },
      { key: 'rc', label: 'RC', type: 'text' },
      { key: 'adresse', label: 'Adresse', type: 'text' },
      { key: 'telephone', label: 'Téléphone', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'devise', label: 'Devise', type: 'text', required: true, default: 'BIF' },
      { key: 'date_creation', label: 'Date création', type: 'date' },
      { key: 'actif', label: 'Actif', type: 'boolean', default: true },
    ],
  },
  exercices: {
    createLabel: 'Nouvel exercice',
    editLabel: 'Modifier l’exercice',
    endpoint: 'exercices',
    fields: [
      { key: 'societe_id', label: 'Société', type: 'lookup', lookup: 'societes', required: true },
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'date_debut', label: 'Date début', type: 'date', required: true },
      { key: 'date_fin', label: 'Date fin', type: 'date', required: true },
    ],
  },
  periodes: {
    createLabel: 'Nouvelle période',
    editLabel: 'Modifier la période',
    endpoint: 'periodes',
    fields: [
      { key: 'exercice_id', label: 'Exercice', type: 'lookup', lookup: 'exercices', required: true },
      { key: 'libelle', label: 'Libellé', type: 'text', required: true },
      { key: 'date_debut', label: 'Date début', type: 'date', required: true },
      { key: 'date_fin', label: 'Date fin', type: 'date', required: true },
      { key: 'cloturee', label: 'Clôturée', type: 'boolean', default: false },
    ],
  },
  typeJournaux: {
    createLabel: 'Nouveau type de journal',
    editLabel: 'Modifier le type de journal',
    endpoint: 'type-journals',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
      { key: 'actif', label: 'Actif', type: 'boolean', default: true },
    ],
  },
  typeTiers: {
    createLabel: 'Nouveau type de tiers',
    editLabel: 'Modifier le type de tiers',
    endpoint: 'type-tiers',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
      { key: 'actif', label: 'Actif', type: 'boolean', default: true },
    ],
  },
  typeComptes: {
    createLabel: 'Nouveau type de compte',
    editLabel: 'Modifier le type de compte',
    endpoint: 'type-comptes',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
      { key: 'actif', label: 'Actif', type: 'boolean', default: true },
    ],
  },
  typeBudgets: {
    createLabel: 'Nouveau type de budget',
    editLabel: 'Modifier le type de budget',
    endpoint: 'type-budgets',
    fields: [
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'intitule', label: 'Intitulé', type: 'text', required: true },
      { key: 'actif', label: 'Actif', type: 'boolean', default: true },
    ],
  },
}
